name: PipelineWorkflow

on:
  push:
    branches:
      - main
    pull_request:
      - main

jobs:
  build:
    name: Azure Pipeline
    runs-on: ubuntu-latest
    steps:
    - name: Azure Pipelines Action
      uses: Azure/pipelines@v1
      with:
        azure-devops-project-url: https://dev.azure.com/herveblondeau/DevProject
        azure-pipeline-name: 'herveblondeau.gitapp'
        azure-devops-token: 'mxujd7rk5awlpv7mfjbzfl47tffwqbkx4klken6com5auwhekgqq' # for testing purposes - not valid anymore ;-)

